### ISSUE TITLE
🐛 Seo - Fix page titles

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.Website-v3#170]
Page titles are inconsistent with the old site.

![image](https://user-images.githubusercontent.com/16027480/218055039-bed4a7f8-6c9b-4642-9481-f588530b24e8.png)
**Figure: Title inconsistency example on power bi page**
  

```[tasklist]
### Tasks
- [ ] Fix home page title
- [ ] Fix consulting page titles
- [ ] Fix 404 and other miscellaneous page titles
```
