### ISSUE TITLE
🐛 UG Live Banner styling broken

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#184]
```[tasklist]
### Tasks
- [x] Make text fit on banner
- [x] Make banner full width
- [x] Add minutes to countdown
- [x] Make banner show on mobile phones (portait layout)
- [x] Set up state for isLive for when minutes tick over to live
- [x] Filter to only user group events
```

![Image](https://user-images.githubusercontent.com/38869720/218880387-7985cbde-ef58-481d-9748-0b2054d38f8e.png)
**FIgure: New website 😒**

![Image](https://user-images.githubusercontent.com/38869720/218880655-d82bfdee-6869-49ac-8ef3-7aebfaa9f209.png)
**FIgure: Old website**

This was working, but a styling change must have effected it.
See the done video https://github.com/SSWConsulting/SSW.Website-v3/pull/55#issue-1550224872

**Comment by Harry-Ross** [comment]
As per our conversation, I will try the following:

- [ ] Switch from Day.js to Moment to update countdown timer
- [ ] Test moment with page insights
- [ ] If high impact, write custom code for live update with Day.js

**Comment by Harry-Ross** [comment]
- [ ] Set up state for isLive for when minutes tick over to live
