### ISSUE TITLE
✨ UG Embedded Live stream on home page

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#189]
As per my convesation with the TV team and Piers, the old website has an embedded live stream on the home page when the SSW TV channel is live (streamyard).

```[tasklist]
### Tasks
- [x] Get screenshots of the old website home page when we are live
![image](https://user-images.githubusercontent.com/16027480/219599959-90a3ec1d-29e9-4be2-918c-e33ebf4075e7.png)
**Figure: Sample live stream widget**
- [x] Fetch sharepoint event data from the old site. (Tech debt to be resolved in #51 )
- [x] Create a embed of the live stream to the home page - make this a component that can be added to other pages
```
