### ISSUE TITLE
💸 Consulting Enquiry Form - Implement API

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.Website-v3#219]
The current form is still using the old endpoint when submitted, the submit button won't work before we go live because the function is using relative path and requires the prod domain "ssw.com.au".

![Image](https://user-images.githubusercontent.com/16027480/219602495-21aec20d-f7e9-4a22-9fb2-f6c136bc9a06.png)
**Figure: Submitting the form will receive error**

```[tasklist]
### Tasks
- [x] Submit data to the Azure function / Logic app from #51
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/472
- [ ] https://github.com/SSWConsulting/SSW.Website-v3/issues/502
```

**Comment by amankumarrr** [comment]
@jimmidier I'm not sure about the last task, could you please leave some description with it.

**Comment by amankumarrr** [comment]
Removing the last check (https://github.com/SSWConsulting/SSW.Website-v3/issues/638) and adding it to the tech debt with.
