### ISSUE TITLE
✨ Create SSW Internship Program page

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#34]
This is priority after the core website infra is done

```[tasklist]
### Tasks
- [ ] Create a new page Implementing the Figma designs linked below
- [ ] Add a link to the page on the MegaMenu under Training | SSW Internship Programs | Fullstack developer
- [ ] Add a link to the new page on About Us | Who we are | Employment Opportunities | Current Positions
```

https://www.figma.com/file/6IU1jg9Stosfecs4YfawoR/SSW-Internship-Program

As per my conversation with @pierssinclairssw the new page url should be ssw.com.au/training/internship/fullstack (confirm this with Adam + Camilla)

**Comment by piers-sinclair** [comment]
@BrookJeynes what is the status of this feature?

**Comment by piers-sinclair** [comment]
@BrookJeynes How is this tracking?

**Comment by BrookJeynes** [comment]
CC: @bradystroud 

Hey @pierssinclairssw, sorry for the late response

The page is coming along well! All that's really left now is 
- Fix some style issues and getting updated icons
- Updating the pages content
- Building the event countdown component
- Hooking up the footer "Subscribe to get notified about SSW training programs" to actually subscribe an email (this can be left out for now as from last I recall the subscribe system hasn't been created yet)
 
Since this is an urgent task, If i cant get it done by Tuesday, I'll do a handover and assign it to another dev



![Image](https://user-images.githubusercontent.com/25432120/229383182-07f0162b-61a7-44dc-b4b5-63b9069c31f1.png)


![Image](https://user-images.githubusercontent.com/25432120/229383195-de5c5925-0001-46d9-9990-6ea2ce1b9478.png)



![Image](https://user-images.githubusercontent.com/25432120/229383205-039cbfe5-2ca5-4638-8731-abba8f59e81d.png)
