### ISSUE TITLE
Consulting - Migrate technology cards

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#66]
Stored here in the old website
https://github.com/SSWConsulting/SSW.Website.Content/tree/main/technologies

```[tasklist]
### Tasks
- [x] Copy md files from old project
- [x] Do a Find and Replace to put the content in the new format
- [x] Do a Find and Replace to update the paths in the consulting page
- [ ] Update all image references
```
