### ISSUE TITLE
💄 Consulting template - Clean up UI

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#69]
After building and adding multiple components to the consulting page, there is are some touch ups needed to make it look like the old site.

```[tasklist]
### Tasks
- [x] Fix section backgrounds
- [x] Add red seperators
- [ ] Check component order
- [ ] Resolve testimonials render error
```

![Image](https://user-images.githubusercontent.com/38869720/215004851-c84da7cb-e8ee-4ed0-a1f1-db07bee97055.png)
**Figure: White background needs to be full width (I think the parallax image need to have a fixed height)**

![Image](https://user-images.githubusercontent.com/38869720/215005016-5a408610-0cc8-422a-9835-3030e2aa66c0.png)
**Figure: Need to add red seperator between sections**

![image](https://user-images.githubusercontent.com/16027480/215940222-502dd21d-61e2-4b04-b40f-1ac50b6d09c8.png)
**Figure: Render error occured on consulting page**
