### ISSUE TITLE
💄 Designer review

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website-v3#70]
```[tasklist]
### Tasks
- [x] Get a designer (Joseph then Tiago) to review the new website, ensuring it looks and behaves like the old website (e.g. is every page responsive)
- [ ] Fix any issues they may present
- [x] Get a rating
- [ ] Get a yes/no if its ready to go live
```

This should happen before the gatsby pages are replaced

**Comment by BrookJeynes** [comment]
Here is the feedback as per my conversation with Tiago.

## Homepage
1. The Logo and tagline in the new site are smaller than in the current
2. The new site is missing the carousel
3. Socials in the header are smaller and have more padding in the new

    ![Image](https://user-images.githubusercontent.com/25432120/216485363-78ac50bb-fad3-4ac1-bff6-3f11285635f8.png)
**Figure: New site socials**

    ![Image](https://user-images.githubusercontent.com/25432120/216485414-7160dd05-db02-4a0d-b828-bf8a96f3617f.png)
**Figure: Current site socials**

4. Text height is too high in the new site vs the current
  
    ![Image](https://user-images.githubusercontent.com/25432120/216485568-73d06c30-c9a1-48d6-b3b1-5da79b9fedd0.png)
**Figure: New site line-height**

    ![Image](https://user-images.githubusercontent.com/25432120/216485605-f6ff829a-681c-4119-bfa1-e3b10bf9dd18.png)
**Figure: Current site line-height**

5. Upcoming events component doesn't span the full section height

    ![Image](https://user-images.githubusercontent.com/25432120/216485753-8ae7010b-9b87-42b2-b3ee-e996cd529f88.png)
**Figure: New site "Upcoming Events" widget**

    ![Image](https://user-images.githubusercontent.com/25432120/216485836-2a1ffe19-7ca6-4e21-845f-445b930cfe95.png)
**Figure: Current site "Upcoming Events" widget**

6. Map is missing state names

    ![Image](https://user-images.githubusercontent.com/25432120/216486476-1334ea4d-d274-48f5-a961-fddebf8f8b64.png)
**Figure: New site missing state text**

    ![Image](https://user-images.githubusercontent.com/25432120/216486533-5d5a6f8f-699c-4825-b1a8-51a4375bc924.png)
**Figure: Current site with state text**

7. "Contact Us" component using incorrect icons and missing icon transition on hover

    ![Image](https://user-images.githubusercontent.com/25432120/216486625-27605946-ac48-495e-a258-77c1f98c3ba0.png)
**Figure: New site with arrows icon + missing hover animation**

    ![Image](https://user-images.githubusercontent.com/25432120/216486658-d6210345-1b48-4771-9ef4-9529c2d9f3e0.png)
**Figure: Current site with chevron icon + hover animation**


8. "Build on Microsoft Azure Platform" component hidden by footer

    ![Image](https://user-images.githubusercontent.com/25432120/216486260-32f87e85-0971-49ad-b0fc-d47a5c536c2a.png)
**Figure: Component hidden by footer**

9. Map disappears too early when enlarging screen + components aren't left aligned + YouTube video doesn't disappear

    ![Image](https://user-images.githubusercontent.com/25432120/216487024-cfb31d8d-31c9-417b-965c-bd49400f46e0.png)
**Figure: New site with incorrect positioning and map gone**

    ![Image](https://user-images.githubusercontent.com/25432120/216487049-7e1d0504-2cd7-4cda-b14f-4592d973c26f.png)
**Figure: Current site with correct positioning and map still showing**

10. When zoomed in far enough on the current site the "Upcoming Events" widget spans the full screen width and replaces the "Australia's Leading .NET and Azure Consultants" information. This does not happen on the new site.

    ![Image](https://user-images.githubusercontent.com/25432120/216487376-c43759e6-e2bf-41ac-8e92-6749faa82a35.png)
**Figure: New site**

    ![Image](https://user-images.githubusercontent.com/25432120/216487399-7e70396d-7806-4d24-b554-5d3355cf8d5c.png)
**Figure: Current site**

**Comment by tkapa** [comment]
Closing as I've added all of these problems to separate issues. 

We should go back to Tiago and Joe once we've finished those bugs.
